export const data = [
    {
        name: 'ハルカ',
        singer: 'YOASOBI',
        year: 2020,
        lyrics: '君のよろこびは ボクのよろこびで 君の大切が幸せが いつまでも君とありますように',
        cover: 'artwork/1.jpg',
        song: 'music/1.mp3',
    },
    {
        name: 'ただ君に晴れ',
        singer: 'ヨルシカ',
        year: 2018,
        lyrics: '写真なんて紙切れだ 思い出なんてただの塵だ それがわからないから、口を噤んだまま',
        cover: 'artwork/2.jpg',
        song: 'music/2.mp3',
    },
    {
        name: '世界に一つだけの花',
        singer: 'SMAP',
        year: 2002,
        lyrics: '名前も知らなかったけれど あの日ボクに笑顔をくれた 誰も気づかないような場所で咲いていた 花のように',
        cover: 'artwork/3.jpg',
        song: 'music/3.mp3',
    },
    {
        name: 'マリーゴールド',
        singer: 'あいみょん',
        year: 2019,
        lyrics: '柔らかな肌を寄せあい 少し冷たい空気を2人 かみしめて歩く 今日という日に 何と 名前をつけようかなんて話して',
        cover: 'artwork/4.jpg',
        song: 'music/4.mp3',
    },
    {
        name: 'キセキ',
        singer: 'GReeeeN',
        year: 2008,
        lyrics: 'いつも君の右の手の平を ただ僕の左の手の平が そっと包んでくそれだけで ただ愛を感じていた',
        cover: 'artwork/5.jpg',
        song: 'music/5.mp3',
    },
    {
        name: 'Best Friend',
        singer: '西野カナ',
        year: 2010,
        lyrics: '泣きたい時はおもいっきり泣けばいい 側にいるからって 誰よりも強い味方 そんな君に私は何かしてあげられてるかな？',
        cover: 'artwork/6.jpg',
        song: 'music/6.mp3',
    },
    {
        name: '白日',
        singer: 'King Gnu',
        year: 2019,
        lyrics: '真っ白に全てさよなら 降りしきる雪よ 全てを包み込んでくれ 今日だけは 全てを隠してくれ',
        cover: 'artwork/7.jpg',
        song: 'music/7.mp3',
    },
    {
        name: 'アイネクライネ',
        singer: '米津玄師',
        year: 2014,
        lyrics: '誰かの居場所を奪い生きるくらいならばもう あたしは石ころにでもなれたらいいな だとしたら勘違いも戸惑いもない そうやってあなたまでも知らないままで',
        cover: 'artwork/8.jpg',
        song: 'music/8.mp3',
    },
    {
        name: 'Butterfly',
        singer: '木村カエラ',
        year: 2009,
        lyrics: '君は今誓い 愛する人の側で 幸せだよと 微笑んでる 確かなその思いで 鐘が響くよ',
        cover: 'artwork/9.jpg',
        song: 'music/9.mp3',
    },
    {
        name: 'RPG',
        singer: 'SEKAI NO OARI',
        year: 2015,
        lyrics: '街を抜け海に出たら 次はどこを目指そうか 僕らはまた出かけよう 愛しいこの地球を',
        cover: 'artwork/10.jpg',
        song: 'music/10.mp3',
    },
    {
        name: 'あとひとつ',
        singer: 'FUNKY MONKEY BABY’S',
        year: 2011,
        lyrics: 'そう簡単じゃないからこそ 夢はこんなに輝くんだと そう あの日の君の言葉 今でも胸に抱きしめてるよ',
        cover: 'artwork/11.jpg',
        song: 'music/11.mp3',
    },
    {
        name: '雨のち晴レルヤ',
        singer: 'ゆず',
        year: 2013,
        lyrics: '突然偶然 それとも必然 始まりは気付かぬうちに 予報通り いかない模様 そんな時こそ 微笑みを',
        cover: 'artwork/12.jpg',
        song: 'music/12.mp3',
    },
    {
        name: 'Rising Sun',
        singer: 'EXILE',
        year: 2011,
        lyrics: 'どんな暗い 闇の中でも 明けない夜はないと 信じて 未来のため 何かを感じてる 先が見えない 旅だとしても この鼓動が 止まる日まで 決してあきらめないと 誓おう そう今',
        cover: 'artwork/13.jpg',
        song: 'music/13.mp3',
    },
    {
        name: 'タカラモノ ~この声がなくなるまで~',
        singer: 'ナオト・インティライミ',
        year: 2010,
        lyrics: 'キミのことずっと いつだって 守り続ける キミが寂しくないように こんな歌を歌うよ この声がなくなるまで',
        cover: 'artwork/14.jpg',
        song: 'music/14.mp3',
    },
    {
        name: '気まぐれロマンティック',
        singer: 'いきものがかり',
        year: 2008,
        lyrics: 'ホントは 本気であたしを 叱ってくれる大事なひと なんて言ったらアイツは 得意気になるから もう褒めたりしない',
        cover: 'artwork/15.jpg',
        song: 'music/15.mp3',
    },
]
